//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiamtradeAdminEntities : DbContext
    {
        public DiamtradeAdminEntities()
            : base("name=DiamtradeAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mst_AboutUS> Mst_AboutUS { get; set; }
        public virtual DbSet<Mst_Career> Mst_Career { get; set; }
        public virtual DbSet<Mst_CareersSend> Mst_CareersSend { get; set; }
        public virtual DbSet<Mst_CarrerMulti> Mst_CarrerMulti { get; set; }
        public virtual DbSet<Mst_Cloud> Mst_Cloud { get; set; }
        public virtual DbSet<Mst_Cloud_Features> Mst_Cloud_Features { get; set; }
        public virtual DbSet<Mst_Cloud_Gallery> Mst_Cloud_Gallery { get; set; }
        public virtual DbSet<Mst_Cloud_Inventories> Mst_Cloud_Inventories { get; set; }
        public virtual DbSet<Mst_Cloud_KetFeature> Mst_Cloud_KetFeature { get; set; }
        public virtual DbSet<Mst_CloudFeature> Mst_CloudFeature { get; set; }
        public virtual DbSet<Mst_Compare> Mst_Compare { get; set; }
        public virtual DbSet<Mst_Compare_KeyFeature> Mst_Compare_KeyFeature { get; set; }
        public virtual DbSet<Mst_CompareMaster> Mst_CompareMaster { get; set; }
        public virtual DbSet<Mst_ContactUs> Mst_ContactUs { get; set; }
        public virtual DbSet<Mst_CotactMessage> Mst_CotactMessage { get; set; }
        public virtual DbSet<Mst_DemoRequest> Mst_DemoRequest { get; set; }
        public virtual DbSet<Mst_DeskFeature> Mst_DeskFeature { get; set; }
        public virtual DbSet<Mst_Desktop> Mst_Desktop { get; set; }
        public virtual DbSet<Mst_Desktop_Features> Mst_Desktop_Features { get; set; }
        public virtual DbSet<Mst_Desktop_Gallery> Mst_Desktop_Gallery { get; set; }
        public virtual DbSet<Mst_Desktop_Inventories> Mst_Desktop_Inventories { get; set; }
        public virtual DbSet<Mst_Desktop_KeyFeature> Mst_Desktop_KeyFeature { get; set; }
        public virtual DbSet<Mst_Diamx> Mst_Diamx { get; set; }
        public virtual DbSet<Mst_DiamX_Features> Mst_DiamX_Features { get; set; }
        public virtual DbSet<Mst_Diamx_Gallery> Mst_Diamx_Gallery { get; set; }
        public virtual DbSet<Mst_Diamx_Inventories> Mst_Diamx_Inventories { get; set; }
        public virtual DbSet<Mst_Diamx_KeyFeature> Mst_Diamx_KeyFeature { get; set; }
        public virtual DbSet<Mst_Footerblock> Mst_Footerblock { get; set; }
        public virtual DbSet<Mst_Home> Mst_Home { get; set; }
        public virtual DbSet<Mst_Inquiry> Mst_Inquiry { get; set; }
        public virtual DbSet<Mst_InquiryMessage> Mst_InquiryMessage { get; set; }
        public virtual DbSet<Mst_KeyFeatures> Mst_KeyFeatures { get; set; }
        public virtual DbSet<Mst_OurClientImages> Mst_OurClientImages { get; set; }
        public virtual DbSet<Mst_Product> Mst_Product { get; set; }
        public virtual DbSet<Mst_Service_Features> Mst_Service_Features { get; set; }
        public virtual DbSet<Mst_ServiceContent> Mst_ServiceContent { get; set; }
        public virtual DbSet<Mst_Services> Mst_Services { get; set; }
        public virtual DbSet<Mst_ServicesType> Mst_ServicesType { get; set; }
        public virtual DbSet<Mst_Slider> Mst_Slider { get; set; }
        public virtual DbSet<Mst_Support> Mst_Support { get; set; }
        public virtual DbSet<Mst_TabImage> Mst_TabImage { get; set; }
        public virtual DbSet<Mst_TabMaster> Mst_TabMaster { get; set; }
        public virtual DbSet<Mst_Testimonial> Mst_Testimonial { get; set; }
        public virtual DbSet<Mst_Testimonial_New> Mst_Testimonial_New { get; set; }
        public virtual DbSet<Mst_TestimonialMain> Mst_TestimonialMain { get; set; }
        public virtual DbSet<Mst_User> Mst_User { get; set; }
    }
}
