//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_DeskFeature
    {
        public int DeskFeatureID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string Feature1 { get; set; }
        public string Feature2 { get; set; }
        public string Feature3 { get; set; }
        public string Feature4 { get; set; }
        public string Feature5 { get; set; }
        public string Feature6 { get; set; }
        public string Feature7 { get; set; }
        public string Feature8 { get; set; }
        public string Img_1 { get; set; }
        public string Img_2 { get; set; }
        public string Img_3 { get; set; }
        public string Img_4 { get; set; }
        public string Img_5 { get; set; }
        public string Img_6 { get; set; }
        public string Img_7 { get; set; }
        public string Img_8 { get; set; }
    }
}
