//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_TestimonialMain
    {
        public int TestMID { get; set; }
        public string img_1 { get; set; }
        public string name_1 { get; set; }
        public string Content_1 { get; set; }
        public string img_2 { get; set; }
        public string name_2 { get; set; }
        public string Content_2 { get; set; }
        public string img_3 { get; set; }
        public string name_3 { get; set; }
        public string Content_3 { get; set; }
        public string img_4 { get; set; }
        public string name_4 { get; set; }
        public string Content_4 { get; set; }
        public string img_5 { get; set; }
        public string name_5 { get; set; }
        public string Content_5 { get; set; }
        public string img_6 { get; set; }
        public string name_6 { get; set; }
        public string Content_6 { get; set; }
        public string img_7 { get; set; }
        public string name_7 { get; set; }
        public string Content_7 { get; set; }
        public string img_8 { get; set; }
        public string name_8 { get; set; }
        public string Content_8 { get; set; }
    }
}
