//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Footerblock
    {
        public int FooterID { get; set; }
        public string FooterAddress { get; set; }
        public string PhoneNo { get; set; }
        public string SupportNo { get; set; }
    }
}
