//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_CareersSend
    {
        public int SendCarrerID { get; set; }
        public string Prefix { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Educations { get; set; }
        public string Designation { get; set; }
        public string CoreExpert { get; set; }
        public string Exper { get; set; }
        public string PrevCompany { get; set; }
        public string CurrentCompany { get; set; }
        public string CurrentSalary { get; set; }
        public string ExpectedSalary { get; set; }
        public string Reference { get; set; }
        public string AttachDoc { get; set; }
        public string AttachPhoto { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
