//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Support
    {
        public int SupportID { get; set; }
        public string Image_Banner { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
        public string Title1 { get; set; }
        public string SubTitle { get; set; }
        public string mobileNo { get; set; }
        public string SupportName { get; set; }
        public string EmailID { get; set; }
        public string Content3 { get; set; }
        public string Title2 { get; set; }
        public string Content4 { get; set; }
    }
}
