//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_AboutUS
    {
        public int AboutID { get; set; }
        public string AboutTitle { get; set; }
        public string AboutContent { get; set; }
        public string AboutTitle1 { get; set; }
        public string AboutContent1 { get; set; }
        public string AboutTitle2 { get; set; }
        public string AboutContent2 { get; set; }
        public string AboutTitle3 { get; set; }
        public string AboutContent3 { get; set; }
        public string AboutTitle4 { get; set; }
        public string AboutContent4 { get; set; }
        public string Image_Banner { get; set; }
        public string Image_Business { get; set; }
        public string Image_Access { get; set; }
        public string Image_Safest_Fastest { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
