//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Home
    {
        public int HomePageID { get; set; }
        public string Title1 { get; set; }
        public string SubTitle1 { get; set; }
        public string Content1 { get; set; }
        public string Title2 { get; set; }
        public string Content2 { get; set; }
        public string Title3 { get; set; }
        public string Content3 { get; set; }
        public string Image_1 { get; set; }
        public string Image_2 { get; set; }
        public string Title4 { get; set; }
        public string Content4 { get; set; }
        public string Image_4 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
    }
}
