//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_ServiceContent
    {
        public int Service_Id { get; set; }
        public string ServiceName { get; set; }
        public string ServiceBanner { get; set; }
        public string Service_Heading { get; set; }
        public string Service_Desc1 { get; set; }
        public string Service_Desc2 { get; set; }
        public string Service_img1 { get; set; }
        public string Service_img2 { get; set; }
        public string Service_ing3 { get; set; }
        public string img1_Content1 { get; set; }
        public string img2_Conrent2 { get; set; }
        public string img3_Content3 { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
