//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Service_Features
    {
        public int Service_Features_Id { get; set; }
        public Nullable<int> ServiceType_Id { get; set; }
        public string Service_Feature_Title { get; set; }
        public string Service_Freature_img { get; set; }
        public string Service_Feature_Desc { get; set; }
    
        public virtual Mst_ServicesType Mst_ServicesType { get; set; }
    }
}
