//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_ServicesType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_ServicesType()
        {
            this.Mst_Service_Features = new HashSet<Mst_Service_Features>();
        }
    
        public int ServiceTypeID { get; set; }
        public string ServiceType { get; set; }
        public string ServiceTypeImage { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ServiceBanner { get; set; }
        public string Service_Heading { get; set; }
        public string Service_Desc1 { get; set; }
        public string Service_Desc2 { get; set; }
        public string Service_img1 { get; set; }
        public string Service_img2 { get; set; }
        public string Service_ing3 { get; set; }
        public string img1_Content1 { get; set; }
        public string img2_Conrent2 { get; set; }
        public string img3_Content3 { get; set; }
        public string Service_title1 { get; set; }
        public string Service_title2 { get; set; }
        public string Service_title3 { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mst_Service_Features> Mst_Service_Features { get; set; }
    }
}
