//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamtrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Compare
    {
        public int CompareID { get; set; }
        public string CompareDesc { get; set; }
        public string Product1Desc { get; set; }
        public string Product2Desc { get; set; }
    }
}
